import babel from "rollup-plugin-babel";
import alias from "rollup-plugin-alias";
import commonjs from "rollup-plugin-commonjs";

export default {
  entry: "src/index.js",
  plugins: [
    alias({
      "yoga-layout": "./Yoga.bundle.js",
    }),
    commonjs({
      namedExports: {
        "src/Yoga.bundle.js": [
          "Node",
          "ALIGN_COUNT",
          "ALIGN_AUTO",
          "ALIGN_FLEX_START",
          "ALIGN_CENTER",
          "ALIGN_FLEX_END",
          "ALIGN_STRETCH",
          "ALIGN_BASELINE",
          "ALIGN_SPACE_BETWEEN",
          "ALIGN_SPACE_AROUND",
          "DIMENSION_COUNT",
          "DIMENSION_WIDTH",
          "DIMENSION_HEIGHT",
          "DIRECTION_COUNT",
          "DIRECTION_INHERIT",
          "DIRECTION_LTR",
          "DIRECTION_RTL",
          "DISPLAY_COUNT",
          "DISPLAY_FLEX",
          "DISPLAY_NONE",
          "EDGE_COUNT",
          "EDGE_LEFT",
          "EDGE_TOP",
          "EDGE_RIGHT",
          "EDGE_BOTTOM",
          "EDGE_START",
          "EDGE_END",
          "EDGE_HORIZONTAL",
          "EDGE_VERTICAL",
          "EDGE_ALL",
          "EXPERIMENTAL_FEATURE_COUNT",
          "EXPERIMENTAL_FEATURE_ROUNDING",
          "EXPERIMENTAL_FEATURE_WEB_FLEX_BASIS",
          "EXPERIMENTAL_FEATURE_MIN_FLEX_FIX",
          "FLEX_DIRECTION_COUNT",
          "FLEX_DIRECTION_COLUMN",
          "FLEX_DIRECTION_COLUMN_REVERSE",
          "FLEX_DIRECTION_ROW",
          "FLEX_DIRECTION_ROW_REVERSE",
          "JUSTIFY_COUNT",
          "JUSTIFY_FLEX_START",
          "JUSTIFY_CENTER",
          "JUSTIFY_FLEX_END",
          "JUSTIFY_SPACE_BETWEEN",
          "JUSTIFY_SPACE_AROUND",
          "LOG_LEVEL_COUNT",
          "LOG_LEVEL_ERROR",
          "LOG_LEVEL_WARN",
          "LOG_LEVEL_INFO",
          "LOG_LEVEL_DEBUG",
          "LOG_LEVEL_VERBOSE",
          "MEASURE_MODE_COUNT",
          "MEASURE_MODE_UNDEFINED",
          "MEASURE_MODE_EXACTLY",
          "MEASURE_MODE_AT_MOST",
          "OVERFLOW_COUNT",
          "OVERFLOW_VISIBLE",
          "OVERFLOW_HIDDEN",
          "OVERFLOW_SCROLL",
          "POSITION_TYPE_COUNT",
          "POSITION_TYPE_RELATIVE",
          "POSITION_TYPE_ABSOLUTE",
          "PRINT_OPTIONS_COUNT",
          "PRINT_OPTIONS_LAYOUT",
          "PRINT_OPTIONS_STYLE",
          "PRINT_OPTIONS_CHILDREN",
          "UNIT_COUNT",
          "UNIT_UNDEFINED",
          "UNIT_POINT",
          "UNIT_PERCENT",
          "UNIT_AUTO",
          "WRAP_COUNT",
          "WRAP_NO_WRAP",
          "WRAP_WRAP",
          "WRAP_WRAP_REVERSE",
        ],
      },
    }),
    babel({
      exclude: "node_modules/**",
    }),
  ],
};
